# This is a basic workflow to help you get started with Actions

name: buildcordova

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
                    
          echo "$ANDROID_HOME is "
          echo $ANDROID_HOME
          echo "$ANDROID_SDK_ROOT is "
          echo $ANDROID_SDK_ROOT
          echo "$PATH is "
          echo $PATH
          echo "$JAVA_HOME is "
          echo $JAVA_HOME
          sudo npm install -g cordova
          cordova create hello com.example.hello HelloWorld
          cd hello
          cordova platform add android@11.0.0
          # https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html
          #cordova requirements
          echo "Platform add complete."
          cordova build android
          
          
